# Generated by Django 2.0.7 on 2018-08-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecureDoomDB', '0002_incident_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=30)),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='street_name', to='SecureDoomDB.Street'),
        ),
    ]
