# Generated by Django 2.0.7 on 2018-08-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureDoomDB', '0003_auto_20180804_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='value',
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.CharField(default='False Alarm', max_length=30),
        ),
    ]
