# Generated by Django 2.0.7 on 2018-08-05 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureDoomDB', '0004_auto_20180804_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='inoutregister',
            name='time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
